import os
from pathlib import Path
import csv


RAW_VCF_MANIFEST = 'gdc_manifests/gbm_raw_vcfs.2018-11-21.txt'
ANNOTATED_VCF_MANIFEST = 'gdc_manifests/gbm_annotated_vcfs.2018-11-26.txt'

SAMPLES = set()
with open(ANNOTATED_VCF_MANIFEST) as f:
    reader = csv.DictReader(f, dialect='excel-tab')
    SAMPLES = set(row['case ID'] for row in reader)

CALLERS = ['varscan2', 'somaticsniper', 'mutect2', 'muse']


rule link_gdc_raw_vcfs:
    """Link the raw GDC VCFs locally."""
    input: manifest=RAW_VCF_MANIFEST
    output: expand('external_data/GDC/raw_vcfs/{sample}.{caller}.vcf.gz', sample=SAMPLES, caller=CALLERS)
    params:
        vcf_root='/diskmnt/Projects/cptac_downloads/gdc_somatic_mutations/unversioned'
    run:
        with open(input['manifest']) as f:
            reader = csv.DictReader(f, dialect='excel-tab')
            for row in reader:
                sample = row['case_submitter_id']
                caller = row['file_name'].split('.')[-4].lower()
                src_vcf_pth = Path(params['vcf_root'], row['id'], row['file_name'])
                dst_pth = Path(f'external_data/GDC/raw_vcfs/{sample}.{caller}.vcf.gz')
                dst_pth.symlink_to(src_vcf_pth)


rule link_gdc_annotated_vcfs:
    """Link the annotated GDC VCFs locally."""
    input: manifest=ANNOTATED_VCF_MANIFEST
    output: expand('external_data/GDC/annotated_vcfs/{sample}.{caller}.vcf.gz', sample=SAMPLES, caller=CALLERS)
    params:
        vcf_root='/diskmnt/Projects/cptac_downloads/gdc_somatic_mutations/unversioned'
    run:
        with open(input['manifest']) as f:
            reader = csv.DictReader(f, dialect='excel-tab')
            for row in reader:
                sample = row['case ID']
                caller = row['file_name'].split('.')[-4].lower()
                src_vcf_pth = Path(params['vcf_root'], row['id'], row['file_name'])
                dst_pth = Path(f'external_data/GDC/annotated_vcfs/{sample}.{caller}.vcf.gz')
                dst_pth.symlink_to(src_vcf_pth)


rule load_raw_vcfs_to_db:
    input: raw_vcfs=rules.link_gdc_raw_vcfs.output
    output: db='processed_data/gdc_mut_calls.sqlite'
    script: 'scripts/make_db.py'
