---
title: "Plot somatic CNV segments"
output: html_notebook
---

```{r, message=FALSE}
library(tidyverse)
library(gtrellis)
```


Load hg38 seqinfo
```{r}
hg38_seqinfo = readRDS('../seqinfo_GRCh38.d1.vd1.rds')
hg38_canonical_seqinfo = keepStandardChromosomes(hg38_seqinfo)

hg38_xlims = tibble(
    chrom = seqnames(hg38_canonical_seqinfo),
    start = 0,  # Same as gtrellis default
    end = seqlengths(hg38_canonical_seqinfo)
) %>%
    filter(chrom != 'chrM')
```

Load cytoband info
```{r}
hg38_cytoband = readRDS('../cytoband_hg38.rds')

# simplify the cytoband
hg38_cytoband <- hg38_cytoband %>%
    filter(chrom %in% seqnames(hg38_canonical_seqinfo)) %>%
    mutate(simplified_cytoband_type = case_when(
        cytoband_type == 'acen' ~ 'centromere',
        startsWith(name, 'p') ~ 'p arm',
        startsWith(name, 'q') ~ 'q arm',
        TRUE ~ NA_character_
    )) %>%
    group_by(chrom, simplified_cytoband_type) %>%
    summarize(start = min(start), end = max(end)) 
```

Customize the cytoband display. showing only the p/q arm and the centrometer location
```{r, fig.width=8, fig.height=3}
cytoband_legend <- ComplexHeatmap::Legend(
    at = c("p arm", "centromere", "q arm"), 
    title = "Cytoband type", 
    type = "grid", 
    legend_gp = gpar(fille = c("gray50", "red", "gray80")),
    background = 'transparent'
)

cytoband_coloring <- function(cytoband_chr) {
    cytoband_chr %>% 
        transmute(
            col = case_when(
                simplified_cytoband_type == 'centromere' ~ rgb(217, 47, 39, maxColorValue = 255),
                simplified_cytoband_type == 'p arm' ~ 'gray50',
                simplified_cytoband_type == 'q arm'~ 'gray80',
                TRUE ~ '#FFFFFF'
            )
        ) %>% 
        pull(col)
}

cytoband_panel_drawer <- function(gr) {
    cytoband_chr = gr
    grid.rect(
        cytoband_chr$start, unit(0, "npc"),
        width = cytoband_chr$end - cytoband_chr$start, height = unit(1, "npc"),
        default.units = "native", hjust = 0, vjust = 0,
        gp = gpar(
            fill = cytoband_coloring(cytoband_chr),
            col = 'transparent'
        ))
    # Plot the block
    grid.rect(
        min(cytoband_chr$start), unit(0, "npc"),
        width = max(cytoband_chr$end) - min(cytoband_chr$start), height = unit(1, "npc"),
        default.units = "native", hjust = 0, vjust = 0,
        gp = gpar(fill = "transparent")
    )
}

gtrellis_layout(
    # species = 'hg38', 
    data = hg38_xlims,
    nrow = 2, compact = TRUE,
    n_track = 2, 
    track_axis = c(FALSE),
    track_height = unit.c(1.5 * grobHeight(textGrob("1XY")), unit(1, 'null')),
    legend = list(cytoband_legend@grob)
)
# Track for chromosome names
add_track(panel_fun = function(gr) {
    chr = str_sub(get_cell_meta_data("name"), start = 4)
    grid.rect(gp = gpar(fill = "#EEEEEE"))
    grid.text(chr, gp = gpar(fontsize = 10))
})
add_track(
    hg38_cytoband, 
    panel_fun = cytoband_panel_drawer
)
```

Read a sample's segment CNV result as a GRanges object:
```{r}
read_seg_cnv <- function(pth) {
    seg_cnv_tbl <- read_tsv(
        pth,
        col_types = cols(
            .default = col_double(),
            chrom = col_character(),
            start = col_integer(),
            end = col_integer(),
            binNum = col_integer()
        )
    ) %>%
        mutate(cnv_status = case_when(
            `log2.copyRatio` >= 0.2 ~ 'Gain',
            `log2.copyRatio` <= -0.2 ~ 'Loss',
            TRUE ~ 'Neutral'
        ))
    seg_cnv_gr <- GRanges(
        seqnames = seg_cnv_tbl$chrom,
        ranges = IRanges(start = seg_cnv_tbl$start, end = seg_cnv_tbl$end),
        strand = "*",
        cnv_log2 = seg_cnv_tbl$log2.copyRatio,
        cnv_status = seg_cnv_tbl$cnv_status,
        seqinfo = hg38_seqinfo
    )
    seg_cnv_gr
}
```


## Plot segment CNV of one sample
```{r}
sample = 'C3L-00365'
seg_cnv_pth = str_interp('../external_data/bicseq2_cnv/segment/${sample}.tsv.gz')
seg_cnv_gr = read_seg_cnv(seg_cnv_pth)
```

```{r, fig.width=9, fig.height=6}
cnv_status_legend <- ComplexHeatmap::Legend(
    at = c("Gain (>0.2)", "Neutral", "Loss (<-0.2)"), 
    title = "CN status", 
    type = "lines", 
    legend_gp = gpar(col = c("red", "gray60", "blue"), lwd = 4),
    background = 'transparent'
)

gtrellis_layout(
    # species = 'hg38', 
    data = hg38_xlims,
    n_track = 3,
    track_axis = c(FALSE, TRUE, FALSE),
    track_height = unit.c(1.5 * grobHeight(textGrob("1XY")), unit(1, "null"), unit(4, 'mm')),
    nrow = 3, compact = TRUE,
    xlab = NULL,
    track_ylab = c('', 'CN log2 ratio', ''),
    track_ylim = c(
        range(seg_cnv_gr$cnv_log2)
    ),
    legend = list(cnv_status_legend@grob, cytoband_legend@grob),
    title = str_interp('Somatic copy number ratio of ${sample}')
)
# Track for chromosome names
add_track(panel_fun = function(gr) {
    chr = str_sub(get_cell_meta_data("name"), start = 4)
    grid.rect(gp = gpar(fill = "#EEEEEE"))
    grid.text(chr, gp = gpar(fontsize = 10))
})
# Track for CNV ratios
add_segments_track(
    seg_cnv_gr, 
    seg_cnv_gr$cnv_log2,
    gp = gpar(
        col = case_when(
            seg_cnv_gr$cnv_status == 'Gain' ~ "red",
            seg_cnv_gr$cnv_status == 'Loss' ~ "blue",
            TRUE ~ "gray60"
        ),
        lwd = 4
    )
)
# Track for cytoband
add_track(
    hg38_cytoband, 
    panel_fun = cytoband_panel_drawer
)
```


## Plot all samples together
```{r}
all_samples <- tibble(
    seg_cnv_pth = list.files('../external_data/bicseq2_cnv/segment', full.names = TRUE)
) %>%
    mutate(sample = str_sub(seg_cnv_pth, start = -16, end = -8))
```

```{r}
all_samples_gr <- purrr::pmap(all_samples, function(sample, seg_cnv_pth) read_seg_cnv(seg_cnv_pth)) %>%
    set_names(nm = all_samples$sample)
```

```{r}
num_samples = length(all_samples_gr)

heatmap_col_fun = circlize::colorRamp2(c(-1, -0.1, 0, 0.1, 1), c('blue', 'white', 'white', 'white', 'red'))
cnv_heatmap_legend = ComplexHeatmap::Legend(
    col_fun = heatmap_col_fun, 
    at = c(-1, -0.2, 0, 0.2, 1),
    labels = c('-1', 'Loss (-0.2)', 'Neutral', 'Gain (0.2)', '1'),
    title = "CN status",
    legend_height = unit(2.5, "cm")
)

# pdf('../processed_data/seg_cnv_all_chroms_all_samples.pdf', width = 20, height = 10)
pdf('../processed_data/seg_cnv_chr1_chr19_all_samples.pdf', width = 10, height = 10)
gtrellis_layout(
    data = hg38_xlims %>% filter(chrom %in% c('chr1', 'chr19')),
    # data = hg38_xlims,
    n_track = 2 + num_samples,
    track_axis = FALSE,
    track_height = unit.c(
        1.5 * grobHeight(textGrob("1XY")), 
        rep(unit(1, "null"), num_samples), 
        unit(4, 'mm')
    ),
    track_ylab = c('', names(all_samples_gr)[1:num_samples], ''),
    lab_fontsize = 8,
    # nrow = 2, compact = TRUE,
    xlab = NULL,
    legend = list(cnv_heatmap_legend@grob, cytoband_legend@grob),
    title = str_interp('Somatic copy number ratio of all GBM samples'),
    padding = unit(c(2, 10, 2, 2), "mm")
)
# Track for chromosome names
add_track(panel_fun = function(gr) {
    chr = str_sub(get_cell_meta_data("name"), start = 4)
    grid.rect(gp = gpar(fill = "#EEEEEE"))
    grid.text(chr, gp = gpar(fontsize = 10))
})
for (i in 1:num_samples) {
    seg_cnv_gr = all_samples_gr[[i]]
    # Track for CNV ratios
    add_heatmap_track(
        seg_cnv_gr, 
        seg_cnv_gr$cnv_log2,
        fill = heatmap_col_fun
    )
}
# Track for cytoband
add_track(
    hg38_cytoband, 
    panel_fun = cytoband_panel_drawer
)
dev.off()
```

