---
title: "R Notebook"
output: html_notebook
---

```{r, message=FALSE}
library(tidyverse)
```

Read cohort sequence availability table
```{r}
cohort_seq_tbl <- read_tsv('../tracked_results/cptac3_gbm_seq_status.tsv')
```

Read MGI BAM map
```{r}
mgi_bam_tbl = read_tsv('../../matt_catalog/MGI.BamMap.dat')
```



## Find cases to run somatic mutation

Cases with GDC harmonized data before:
```{r}
cases_with_gdc_bam_tindaisy = read_tsv('../../201904_locate_adhoc_data/tracked_results/harmonized_tindaisy_vcfs.tsv') %>%
    pull(`# case`)
```

Make sure all the remaining discovery tumor has gdc wxs BAMs
```{r}
cohort_seq_tbl.to_run_tindaisy = cohort_seq_tbl %>%
    filter(in_discovery, !is_gtex_normal) %>% 
    filter(!case %in% cases_with_gdc_bam_tindaisy) 

cohort_seq_tbl.to_run_tindaisy %>%
    count(has_wxs_normal_gdc, has_wxs_tumor_gdc)
```

Make sure all the BAMs are on MGI:
```{r}
mgi_bam_tbl %>%
    filter(case %in% cohort_seq_tbl.to_run_tindaisy$case,
           experimental_strategy == 'WXS', data_format == 'BAM', reference == 'hg38') %>%
    count(sample_type)
```

```{r}
cohort_seq_tbl.to_run_tindaisy %>% pull(case) %>%
    write_lines('../tracked_results/cases_to_run_somatic_mutation.list')
```



## Find cases to run CNV
```{r}
cases_with_cnv <- read_lines(
    '../genomic_downstream_availability/wustl_somatic_cnv_cases.list'
)
```

```{r}
cases_to_run_cnv <- wgs_custom_bam_tbl %>% pull(case) %>% unique() %>% setdiff(cases_with_cnv)
cases_to_run_cnv
```

```{r}
cohort_seq_tbl %>%
    filter(
        !case %in% union(cases_with_cnv, cases_to_run_cnv),
        has_wgs_normal_raw & has_wgs_tumor_raw,
        !is_gtex_normal
    ) %>% 
    select(case, in_discovery)
```

```{r}
cases_to_run_cnv %>%
    write_lines('../tracked_results/cases_to_run_somatic_cnv.list')
```


